version: "3.2"

services: 
  connector-init:
    image: deltampc/delta-chain-connector:dev
    container_name: connector-init
    volumes: 
      - "./connector:/app/"
    command: "init"
  connector:
    image: deltampc/delta-chain-connector:dev
    container_name: connector
    volumes: 
      - "./connector:/app/"

  node1-init:
    image: deltampc/delta-node:dev
    container_name: node1-init
    volumes: 
      - "./node1:/app/"
    command: "init"
  node1-data:
    image: deltampc/delta-node:dev
    container_name: node1-data
    volumes: 
      - "./node1:/app/"
    command: "mnist"
    depends_on: 
      - node1-init
  node1:
    image: deltampc/delta-node:dev
    container_name: node1
    volumes: 
      - "./node1:/app/"
    depends_on: 
      - node1-data
      - connector

  node2-init:
    image: deltampc/delta-node:dev
    container_name: node2-init
    volumes: 
      - "./node2:/app/"
    command: "init"
  node2-data:
    image: deltampc/delta-node:dev
    container_name: node2-data
    volumes: 
      - "./node2:/app/"
    command: "mnist"
    depends_on: 
      - node2-init
  node2:
    image: deltampc/delta-node:dev
    container_name: node2
    volumes: 
      - "./node2:/app/"
    depends_on: 
      - node2-data
      - connector

  dashboard-init:
    image: deltampc/deltaboard:dev
    container_name: dashboard-init
    volumes: 
      - "./dashboard:/app/"
    command: "init"
  dashboard:
    image: deltampc/deltaboard:dev
    container_name: dashboard
    volumes: 
      - "./dashboard:/app/"
    depends_on: 
      - dashboard-init
      - node1
  
  
