---
# configuration of log
log:  
  # log level
  level: "DEBUG"
  # directory for log file
  dir: "logs"

# database connection string. here use sqlite for example, and the sqlite database file is db/delta.db
db: "sqlite+aiosqlite:///db/delta.db"

# configuration of connector
chain_connector:
  # connector host
  host: "connector"
  # connector port
  port: 4500
  # heartbeat interval (seconds)
  heartbeat: 30
  # retry attemps
  retry: 3

# configuration of node http server
node:
  # node name
  name: "node1"
  # node public URL
  url: "http://node1:6700"

# configuration of delta zk
zk:
  # zk host
  host: "zk1"
  # zk port
  port: 3400

# port of node api server
api_port: 6700

# directory for intermediate data and results of task, here is in task for example
task_dir: "task"

# directory for local dataset, here is in data for example
data_dir: "data"
