---
# configuration of log
log:  
  # log level
  level: "INFO"
  # directory for log file
  dir: "logs"

# database connection string. here use sqlite for example, and the sqlite database file is db/delta.db
db: "sqlite:///db/delta.db"

# configuration of blockchain node
chain_connector:
  # blockchain node connection string, required
  address: "connector:4500"

# node address which will be published on blockchain, and other node will connect this node use it
node_address:
  # host of node
  host: "node1"
  # port of node
  port: 6800

# port of the node http server which provides api for deltaboard
api_port: 6700

# directory for intermediate data and results of task, here is in task for example
task_dir: "task"

# directory for local dataset, here is in data for example
data_dir: "data"
